-- ============================================================
-- TripLens Countries Explorer
-- File: 02_roles_and_permissions.sql
-- Purpose: Create dbt and dashboard roles with permissions
-- Run as: ACCOUNTADMIN
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ============================================================
-- 1. DBT ROLE
-- ============================================================

CREATE ROLE IF NOT EXISTS DBT_ROLE
    COMMENT = 'Role used by dbt and Airflow Cosmos';

-- Warehouse access

GRANT USAGE
ON WAREHOUSE TRIPLENS_WH
TO ROLE DBT_ROLE;

-- Database access

GRANT USAGE
ON DATABASE TRIPLENS
TO ROLE DBT_ROLE;

-- RAW schema access

GRANT USAGE
ON SCHEMA TRIPLENS.RAW
TO ROLE DBT_ROLE;

GRANT SELECT
ON ALL TABLES IN SCHEMA TRIPLENS.RAW
TO ROLE DBT_ROLE;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA TRIPLENS.RAW
TO ROLE DBT_ROLE;

-- BRONZE schema access

GRANT USAGE
ON SCHEMA TRIPLENS.BRONZE
TO ROLE DBT_ROLE;

GRANT CREATE TABLE, CREATE VIEW
ON SCHEMA TRIPLENS.BRONZE
TO ROLE DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN SCHEMA TRIPLENS.BRONZE
TO ROLE DBT_ROLE;

GRANT SELECT
ON ALL VIEWS IN SCHEMA TRIPLENS.BRONZE
TO ROLE DBT_ROLE;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA TRIPLENS.BRONZE
TO ROLE DBT_ROLE;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA TRIPLENS.BRONZE
TO ROLE DBT_ROLE;

-- SILVER schema access

GRANT USAGE
ON SCHEMA TRIPLENS.SILVER
TO ROLE DBT_ROLE;

GRANT CREATE TABLE, CREATE VIEW
ON SCHEMA TRIPLENS.SILVER
TO ROLE DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN SCHEMA TRIPLENS.SILVER
TO ROLE DBT_ROLE;

GRANT SELECT
ON ALL VIEWS IN SCHEMA TRIPLENS.SILVER
TO ROLE DBT_ROLE;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA TRIPLENS.SILVER
TO ROLE DBT_ROLE;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA TRIPLENS.SILVER
TO ROLE DBT_ROLE;

-- GOLD schema access

GRANT USAGE
ON SCHEMA TRIPLENS.GOLD
TO ROLE DBT_ROLE;

GRANT CREATE TABLE, CREATE VIEW
ON SCHEMA TRIPLENS.GOLD
TO ROLE DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN SCHEMA TRIPLENS.GOLD
TO ROLE DBT_ROLE;

GRANT SELECT
ON ALL VIEWS IN SCHEMA TRIPLENS.GOLD
TO ROLE DBT_ROLE;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA TRIPLENS.GOLD
TO ROLE DBT_ROLE;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA TRIPLENS.GOLD
TO ROLE DBT_ROLE;

-- ANALYTICS schema access

GRANT USAGE
ON SCHEMA TRIPLENS.ANALYTICS
TO ROLE DBT_ROLE;

GRANT CREATE TABLE, CREATE VIEW
ON SCHEMA TRIPLENS.ANALYTICS
TO ROLE DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN SCHEMA TRIPLENS.ANALYTICS
TO ROLE DBT_ROLE;

GRANT SELECT
ON ALL VIEWS IN SCHEMA TRIPLENS.ANALYTICS
TO ROLE DBT_ROLE;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA TRIPLENS.ANALYTICS
TO ROLE DBT_ROLE;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA TRIPLENS.ANALYTICS
TO ROLE DBT_ROLE;

-- Assign DBT_ROLE to the dbt service user

GRANT ROLE DBT_ROLE
TO USER DBT;

-- ============================================================
-- 2. DASHBOARD ANALYST ROLE
-- ============================================================

CREATE ROLE IF NOT EXISTS TRIPLENS_ANALYST_ROLE
    COMMENT = 'Read-only dashboard role for Power BI and Tableau';

GRANT USAGE
ON WAREHOUSE TRIPLENS_WH
TO ROLE TRIPLENS_ANALYST_ROLE;

GRANT USAGE
ON DATABASE TRIPLENS
TO ROLE TRIPLENS_ANALYST_ROLE;

GRANT USAGE
ON SCHEMA TRIPLENS.ANALYTICS
TO ROLE TRIPLENS_ANALYST_ROLE;

GRANT SELECT
ON ALL TABLES IN SCHEMA TRIPLENS.ANALYTICS
TO ROLE TRIPLENS_ANALYST_ROLE;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA TRIPLENS.ANALYTICS
TO ROLE TRIPLENS_ANALYST_ROLE;

GRANT SELECT
ON ALL VIEWS IN SCHEMA TRIPLENS.ANALYTICS
TO ROLE TRIPLENS_ANALYST_ROLE;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA TRIPLENS.ANALYTICS
TO ROLE TRIPLENS_ANALYST_ROLE;

-- Assign the dashboard role to your Snowflake user

GRANT ROLE TRIPLENS_ANALYST_ROLE
TO USER MADESINA2025;

-- ============================================================
-- 3. VERIFY ROLE ASSIGNMENTS
-- ============================================================

SHOW GRANTS TO ROLE DBT_ROLE;

SHOW GRANTS TO ROLE TRIPLENS_ANALYST_ROLE;

SHOW GRANTS TO USER DBT;

SHOW GRANTS TO USER MADESINA2025;